package giococompitoMVC.vc;
import giococompitoMVC.model.Model;
import javax.swing.JOptionPane;
/**
 *
 * @author Vittorio Privitera
 */
public class MainGameVC extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGameVC.class.getName());
    private Model model;
    /**
     * Creates new form MainGameVC
     */
    public MainGameVC() {
        initComponents();
        this.model=new Model();
        abilitaDisabilita(false);
    }
    private void abilitaDisabilita(boolean b) //false
    {
        rosso_btn.setEnabled(b);
        verde_btn.setEnabled(b);
        blu_btn.setEnabled(b);
        termina_btn.setEnabled(b);
        inizia_btn.setEnabled(!b);
        tentativo_btn.setEnabled(b);
        pari.setEnabled(b);
        dispari.setEnabled(b);
        sceltaPC_lbl.setText("");
        punteggio_lbl.setText("0");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colori = new javax.swing.ButtonGroup();
        pariOdisp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rosso_btn = new javax.swing.JRadioButton();
        verde_btn = new javax.swing.JRadioButton();
        blu_btn = new javax.swing.JRadioButton();
        inizia_btn = new javax.swing.JButton();
        termina_btn = new javax.swing.JButton();
        tentativo_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sceltaPC_lbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        punteggio_lbl = new javax.swing.JLabel();
        pari = new javax.swing.JRadioButton();
        dispari = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("INDOVINA E VINCI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Dimmi se...");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Colore tra:");

        colori.add(rosso_btn);
        rosso_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rosso_btn.setText("Rosso");

        colori.add(verde_btn);
        verde_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        verde_btn.setText("Verde");

        colori.add(blu_btn);
        blu_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        blu_btn.setText("Blu");

        inizia_btn.setText("INIZIA");
        inizia_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inizia_btnActionPerformed(evt);
            }
        });

        termina_btn.setText("TERMINA");
        termina_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termina_btnActionPerformed(evt);
            }
        });

        tentativo_btn.setText("PROVA");
        tentativo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentativo_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Scelta del PC");

        sceltaPC_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Punti utente:");

        punteggio_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        punteggio_lbl.setText("0");

        pariOdisp.add(pari);
        pari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pari.setText("Pari");

        pariOdisp.add(dispari);
        dispari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dispari.setText("Dispari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tentativo_btn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dispari))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(punteggio_lbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rosso_btn)
                            .addComponent(verde_btn)
                            .addComponent(blu_btn)
                            .addComponent(jLabel3))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sceltaPC_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(125, 125, 125))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(inizia_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(termina_btn)
                .addGap(171, 171, 171))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inizia_btn)
                    .addComponent(termina_btn))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(punteggio_lbl))
                        .addGap(31, 31, 31)
                        .addComponent(tentativo_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(pari)
                            .addComponent(dispari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rosso_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verde_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blu_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(sceltaPC_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termina_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termina_btnActionPerformed
        terminaPartita();
    }//GEN-LAST:event_termina_btnActionPerformed

    private void tentativo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentativo_btnActionPerformed
        if(!this.model.isInGioco()) return;
        if(bottone()=="")
        {
            JOptionPane.showMessageDialog(this,"Non hai selezionato nessun colore, attenzione!!!!");
            return;
        }
        int esito=this.model.gioco(bottone(),pariOdispbtn());
        switch(esito)
        {
            case -9: // non siamo in gioco;
                JOptionPane.showMessageDialog(null,"Non stai giocando");
                this.model.terminaPartita();
                abilitaDisabilita(false);
                break;
            case -8:
                JOptionPane.showMessageDialog(null,"Hai finito con "+this.model.getPunti());
                this.model.terminaPartita();
                abilitaDisabilita(false);
                break;
            default:
            punteggio_lbl.setText(""+this.model.getPunti());
            sceltaPC_lbl.setText(""+this.model.sceltaPc()+" "+this.model.getColorePC());
        } 
    }//GEN-LAST:event_tentativo_btnActionPerformed

    private void inizia_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inizia_btnActionPerformed
       abilitaDisabilita(true);
       this.model.iniziaPartita("10");
    }//GEN-LAST:event_inizia_btnActionPerformed
    
    private void terminaPartita()
    {
        int esito=JOptionPane.showConfirmDialog(rootPane,"Vuoi finire si o no?","Conferma",JOptionPane.YES_OPTION);
        if(JOptionPane.OK_OPTION==esito)
        {
            this.model.terminaPartita();
            abilitaDisabilita(false);
        }
    }
    private String bottone()
    {
        if(rosso_btn.isSelected()) return"Rosso";
        if(verde_btn.isSelected()) return"Verde";
        if(blu_btn.isSelected()) return"Blu";
        return "";
    } 
    
    private String pariOdispbtn()
    {
        if(pari.isSelected())return"Pari";
        if(dispari.isSelected())return"Dispari";
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGameVC().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blu_btn;
    private javax.swing.ButtonGroup colori;
    private javax.swing.JRadioButton dispari;
    private javax.swing.JButton inizia_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton pari;
    private javax.swing.ButtonGroup pariOdisp;
    private javax.swing.JLabel punteggio_lbl;
    private javax.swing.JRadioButton rosso_btn;
    private javax.swing.JLabel sceltaPC_lbl;
    private javax.swing.JButton tentativo_btn;
    private javax.swing.JButton termina_btn;
    private javax.swing.JRadioButton verde_btn;
    // End of variables declaration//GEN-END:variables
}
